// Code generated by goctl. DO NOT EDIT!

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderFieldNames = builder.RawFieldNames(&Order{})
	orderRows       = strings.Join(orderFieldNames, ",")

	orderRowsExpectAutoSet   = strings.Join(stringx.Remove(orderFieldNames, "`id`", "`create_time`", "`update_time`", "`created_at`", "`updated_at`"), ",")
	orderRowsWithPlaceHolder = strings.Join(stringx.Remove(orderFieldNames, "`id`", "`create_time`", "`update_time`", "`created_at`", "`updated_at`"), "=?,") + "=?"

	cacheBalanceOrderIdPrefix      = "cache:balance:order:id:"
	cacheBalanceOrderOrderSnPrefix = "cache:balance:order:orderSn:"
)

type (
	orderModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Order) (sql.Result, error)

		FindOne(ctx context.Context, id uint64) (*Order, error)

		FindOneByOrderSn(ctx context.Context, orderSn string) (*Order, error)

		Update(ctx context.Context, session sqlx.Session, data *Order) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Order) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *Order) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*Order, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Order, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Order, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Order, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Order, error)

		Delete(ctx context.Context, session sqlx.Session, id uint64) error
	}

	defaultOrderModel struct {
		sqlc.CachedConn
		table string
	}

	Order struct {
		Id uint64 `db:"id"`
		// 主键ID

		OrderSn string `db:"order_sn"`
		// Shopee订单号

		ShopId int64 `db:"shop_id"`
		// 店铺ID（Shopee shop_id）

		Platform int64 `db:"platform"`
		// 平台标识：1=Shopee，预留多平台扩展

		Status string `db:"status"`
		// 当前订单状态（UNPAID/READY_TO_SHIP/SHIPPED/...）

		SubStatus sql.NullString `db:"sub_status"`
		// 子状态（细分用，可选）

		TotalAmount float64 `db:"total_amount"`
		// 订单总金额（商品+运费-优惠后）

		ItemAmount float64 `db:"item_amount"`
		// 商品总额（不含运费）

		ShippingFee float64 `db:"shipping_fee"`
		// 运费

		DiscountAmount float64 `db:"discount_amount"`
		// 总优惠金额

		Currency string `db:"currency"`
		// 币种代码，例如：TWD、THB

		BuyerId sql.NullString `db:"buyer_id"`
		// 买家ID（Shopee buyer id）

		ReceiverName sql.NullString `db:"receiver_name"`
		// 收货人姓名

		ReceiverPhone sql.NullString `db:"receiver_phone"`
		// 收货人电话

		ReceiverAddress sql.NullString `db:"receiver_address"`
		// 收货地址（可拆分为省市区+详细地址）

		OrderCreatedAt sql.NullTime `db:"order_created_at"`
		// Shopee订单创建时间

		PaidAt sql.NullTime `db:"paid_at"`
		// 支付时间（状态变为已付款时）

		ShipDeadlineAt sql.NullTime `db:"ship_deadline_at"`
		// 平台最晚出货时间

		ShippedAt sql.NullTime `db:"shipped_at"`
		// 发货时间（交给物流时）

		CompletedAt sql.NullTime `db:"completed_at"`
		// 订单完成时间（交易结束）

		CancelledAt sql.NullTime `db:"cancelled_at"`
		// 订单取消时间

		LastStatusChangeAt sql.NullTime `db:"last_status_change_at"`
		// 最近一次订单状态变更时间

		CancelReason sql.NullString `db:"cancel_reason"`
		// 订单取消原因

		ReturnSn sql.NullString `db:"return_sn"`
		// 退货/退款单号（Shopee return_sn）

		RefundStatus sql.NullString `db:"refund_status"`
		// 退款状态（REQUESTED/APPROVED/REFUND_PAID/...）

		RefundAmount sql.NullFloat64 `db:"refund_amount"`
		// 退款金额

		RefundReason sql.NullString `db:"refund_reason"`
		// 退款/退货原因

		ShippingCarrier sql.NullString `db:"shipping_carrier"`
		// 物流承运商编码或名称

		TrackingNo sql.NullString `db:"tracking_no"`
		// 物流运单号

		ShippingStatus sql.NullString `db:"shipping_status"`
		// 物流状态（可与订单状态解耦）

		ExtRaw sql.NullString `db:"ext_raw"`
		// 最近一次原始推送报文（调试用，可截断）

		CreatedAt time.Time `db:"created_at"`
		// 本地记录创建时间

		UpdatedAt time.Time `db:"updated_at"`
		// 本地记录更新时间

		DeletedAt sql.NullTime `db:"deleted_at"`
		// 逻辑删除时间（NULL表示未删除）

	}
)

func newOrderModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultOrderModel {
	return &defaultOrderModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`order`",
	}
}

func (m *defaultOrderModel) Insert(ctx context.Context, session sqlx.Session, data *Order) (sql.Result, error) {
	data.DeletedAt = sql.NullTime{Valid: false}
	data.Version = 1
	balanceOrderIdKey := fmt.Sprintf("%s%v", cacheBalanceOrderIdPrefix, data.Id)
	balanceOrderOrderSnKey := fmt.Sprintf("%s%v", cacheBalanceOrderOrderSnPrefix, data.OrderSn)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, orderRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.OrderSn, data.ShopId, data.Platform, data.Status, data.SubStatus, data.TotalAmount, data.ItemAmount, data.ShippingFee, data.DiscountAmount, data.Currency, data.BuyerId, data.ReceiverName, data.ReceiverPhone, data.ReceiverAddress, data.OrderCreatedAt, data.PaidAt, data.ShipDeadlineAt, data.ShippedAt, data.CompletedAt, data.CancelledAt, data.LastStatusChangeAt, data.CancelReason, data.ReturnSn, data.RefundStatus, data.RefundAmount, data.RefundReason, data.ShippingCarrier, data.TrackingNo, data.ShippingStatus, data.ExtRaw, data.DeletedAt)
		}
		return conn.ExecCtx(ctx, query, data.OrderSn, data.ShopId, data.Platform, data.Status, data.SubStatus, data.TotalAmount, data.ItemAmount, data.ShippingFee, data.DiscountAmount, data.Currency, data.BuyerId, data.ReceiverName, data.ReceiverPhone, data.ReceiverAddress, data.OrderCreatedAt, data.PaidAt, data.ShipDeadlineAt, data.ShippedAt, data.CompletedAt, data.CancelledAt, data.LastStatusChangeAt, data.CancelReason, data.ReturnSn, data.RefundStatus, data.RefundAmount, data.RefundReason, data.ShippingCarrier, data.TrackingNo, data.ShippingStatus, data.ExtRaw, data.DeletedAt)
	}, balanceOrderIdKey, balanceOrderOrderSnKey)
}

func (m *defaultOrderModel) FindOne(ctx context.Context, id uint64) (*Order, error) {
	balanceOrderIdKey := fmt.Sprintf("%s%v", cacheBalanceOrderIdPrefix, id)
	var resp Order
	err := m.QueryRowCtx(ctx, &resp, balanceOrderIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and deleted_at IS NULL limit 1", orderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderModel) FindOneByOrderSn(ctx context.Context, orderSn string) (*Order, error) {
	balanceOrderOrderSnKey := fmt.Sprintf("%s%v", cacheBalanceOrderOrderSnPrefix, orderSn)
	var resp Order
	err := m.QueryRowIndexCtx(ctx, &resp, balanceOrderOrderSnKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `order_sn` = ? and deleted_at IS NULL limit 1", orderRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, orderSn); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderModel) Update(ctx context.Context, session sqlx.Session, newData *Order) (sql.Result, error) {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return nil, err
	}
	balanceOrderIdKey := fmt.Sprintf("%s%v", cacheBalanceOrderIdPrefix, data.Id)
	balanceOrderOrderSnKey := fmt.Sprintf("%s%v", cacheBalanceOrderOrderSnPrefix, data.OrderSn)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, orderRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.OrderSn, newData.ShopId, newData.Platform, newData.Status, newData.SubStatus, newData.TotalAmount, newData.ItemAmount, newData.ShippingFee, newData.DiscountAmount, newData.Currency, newData.BuyerId, newData.ReceiverName, newData.ReceiverPhone, newData.ReceiverAddress, newData.OrderCreatedAt, newData.PaidAt, newData.ShipDeadlineAt, newData.ShippedAt, newData.CompletedAt, newData.CancelledAt, newData.LastStatusChangeAt, newData.CancelReason, newData.ReturnSn, newData.RefundStatus, newData.RefundAmount, newData.RefundReason, newData.ShippingCarrier, newData.TrackingNo, newData.ShippingStatus, newData.ExtRaw, newData.DeletedAt, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.OrderSn, newData.ShopId, newData.Platform, newData.Status, newData.SubStatus, newData.TotalAmount, newData.ItemAmount, newData.ShippingFee, newData.DiscountAmount, newData.Currency, newData.BuyerId, newData.ReceiverName, newData.ReceiverPhone, newData.ReceiverAddress, newData.OrderCreatedAt, newData.PaidAt, newData.ShipDeadlineAt, newData.ShippedAt, newData.CompletedAt, newData.CancelledAt, newData.LastStatusChangeAt, newData.CancelReason, newData.ReturnSn, newData.RefundStatus, newData.RefundAmount, newData.RefundReason, newData.ShippingCarrier, newData.TrackingNo, newData.ShippingStatus, newData.ExtRaw, newData.DeletedAt, newData.Id)
	}, balanceOrderIdKey, balanceOrderOrderSnKey)
}

func (m *defaultOrderModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, newData *Order) error {

	oldVersion := newData.Version
	newData.Version += 1

	var sqlResult sql.Result
	var err error

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	balanceOrderIdKey := fmt.Sprintf("%s%v", cacheBalanceOrderIdPrefix, data.Id)
	balanceOrderOrderSnKey := fmt.Sprintf("%s%v", cacheBalanceOrderOrderSnPrefix, data.OrderSn)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, orderRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.OrderSn, newData.ShopId, newData.Platform, newData.Status, newData.SubStatus, newData.TotalAmount, newData.ItemAmount, newData.ShippingFee, newData.DiscountAmount, newData.Currency, newData.BuyerId, newData.ReceiverName, newData.ReceiverPhone, newData.ReceiverAddress, newData.OrderCreatedAt, newData.PaidAt, newData.ShipDeadlineAt, newData.ShippedAt, newData.CompletedAt, newData.CancelledAt, newData.LastStatusChangeAt, newData.CancelReason, newData.ReturnSn, newData.RefundStatus, newData.RefundAmount, newData.RefundReason, newData.ShippingCarrier, newData.TrackingNo, newData.ShippingStatus, newData.ExtRaw, newData.DeletedAt, newData.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, newData.OrderSn, newData.ShopId, newData.Platform, newData.Status, newData.SubStatus, newData.TotalAmount, newData.ItemAmount, newData.ShippingFee, newData.DiscountAmount, newData.Currency, newData.BuyerId, newData.ReceiverName, newData.ReceiverPhone, newData.ReceiverAddress, newData.OrderCreatedAt, newData.PaidAt, newData.ShipDeadlineAt, newData.ShippedAt, newData.CompletedAt, newData.CancelledAt, newData.LastStatusChangeAt, newData.CancelReason, newData.ReturnSn, newData.RefundStatus, newData.RefundAmount, newData.RefundReason, newData.ShippingCarrier, newData.TrackingNo, newData.ShippingStatus, newData.ExtRaw, newData.DeletedAt, newData.Id, oldVersion)
	}, balanceOrderIdKey, balanceOrderOrderSnKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultOrderModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *Order) error {
	data.DeletedAt = sql.NullTime{Time: time.Now(), Valid: true}
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "OrderModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultOrderModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("deleted_at IS NULL").ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultOrderModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("deleted_at IS NULL").ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultOrderModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*Order, error) {

	builder = builder.Columns(orderRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("deleted_at IS NULL").ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Order
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultOrderModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Order, error) {

	builder = builder.Columns(orderRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("deleted_at IS NULL").Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Order
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultOrderModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Order, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(orderRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("deleted_at IS NULL").Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*Order
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultOrderModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Order, error) {

	builder = builder.Columns(orderRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("deleted_at IS NULL").OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Order
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultOrderModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Order, error) {

	builder = builder.Columns(orderRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("deleted_at IS NULL").OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Order
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultOrderModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultOrderModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}

func (m *defaultOrderModel) Delete(ctx context.Context, session sqlx.Session, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	balanceOrderIdKey := fmt.Sprintf("%s%v", cacheBalanceOrderIdPrefix, id)
	balanceOrderOrderSnKey := fmt.Sprintf("%s%v", cacheBalanceOrderOrderSnPrefix, data.OrderSn)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, balanceOrderIdKey, balanceOrderOrderSnKey)
	return err
}

func (m *defaultOrderModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheBalanceOrderIdPrefix, primary)
}
func (m *defaultOrderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and deleted_at IS NULL limit 1", orderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOrderModel) tableName() string {
	return m.table
}
